#!/usr/bin/env python3
"""Generate the CLI reference from the console-script's help.

The CLI is small and hand-parsed in `server.main`; its `__doc__` is the help
text. Emitting it here keeps the docs reference generated-from-source and
drift-checked: change the CLI's behavior/docstring and CI regenerates + fails
on drift. Run via `make docs-reference`.
"""

from __future__ import annotations

import pathlib

from bibliocommons_mcp.server import main

OUT = pathlib.Path("docs-mintlify/reference/cli.mdx")

HEADER = """\
---
title: CLI reference
description: The bibliocommons-mcp command-line interface.
---

{/* GENERATED by scripts/gen_cli_reference.py — do not edit by hand. */}

The `bibliocommons-mcp` console script. With no arguments it runs the MCP server
over stdio (for desktop clients); other subcommands are below. See
[Install](/install) for client wiring and [Configuration](/reference/configuration)
for settings.
"""


def main_() -> None:
    help_text = (main.__doc__ or "").strip()
    body = (
        HEADER + "\n```text\nbibliocommons-mcp [subcommand]\n\n" + help_text + "\n```\n"
    )
    OUT.write_text(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main_()
